// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ContactListConsoleApp;
using ContactListConsoleApp.Models;
using Microsoft.Rest;

namespace ContactListConsoleApp
{
    public static partial class ContactsExtensions
    {
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IContacts.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static bool DeleteById(this IContacts operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContacts)s).DeleteByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IContacts.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<bool> DeleteByIdAsync(this IContacts operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<bool> result = await operations.DeleteByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IContacts.
        /// </param>
        public static IList<Contact> Get(this IContacts operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContacts)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IContacts.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Contact>> GetAsync(this IContacts operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<ContactListConsoleApp.Models.Contact>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IContacts.
        /// </param>
        /// <param name='contact'>
        /// Required.
        /// </param>
        public static Contact PostByContact(this IContacts operations, Contact contact)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContacts)s).PostByContactAsync(contact);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IContacts.
        /// </param>
        /// <param name='contact'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Contact> PostByContactAsync(this IContacts operations, Contact contact, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<ContactListConsoleApp.Models.Contact> result = await operations.PostByContactWithOperationResponseAsync(contact, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
