// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ContactListConsoleApp;
using Microsoft.Rest;

namespace ContactListConsoleApp
{
    public static partial class DotNetQuickStartExtensions
    {
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IDotNetQuickStart.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static object GetContactByIdById(this IDotNetQuickStart operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IDotNetQuickStart)s).GetContactByIdByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ContactListConsoleApp.IDotNetQuickStart.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> GetContactByIdByIdAsync(this IDotNetQuickStart operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.GetContactByIdByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
